language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py

services:
  - mysql

before_install:
  - mysql -u root --password="" < test/travis.sql