"""empty message

Revision ID: 0267277282bf
Revises: 656dac64dbea
Create Date: 2019-03-20 16:18:29.128672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0267277282bf'
down_revision = '656dac64dbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abishyuwe', sa.Column('department_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'abishyuwe', 'departments', ['department_id'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abishyuwe', type_='foreignkey')
    op.drop_column('abishyuwe', 'department_id')
    # ### end Alembic commands ###
