"""empty message

Revision ID: 16610378222a
Revises: 5df0783094d3
Create Date: 2019-04-25 18:14:19.216855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16610378222a'
down_revision = '5df0783094d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusarurob', sa.Column('Asigaye', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusarurob', 'Asigaye')
    # ### end Alembic commands ###
