"""empty message

Revision ID: 1a3765dca4d9
Revises: 
Create Date: 2020-08-07 07:34:20.080489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3765dca4d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arc_cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('cooperative_name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('reg_date', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('male_members', sa.String(length=255), nullable=True),
    sa.Column('female_members', sa.String(length=255), nullable=True),
    sa.Column('total_members', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('share_person', sa.String(length=255), nullable=True),
    sa.Column('president_and_contact', sa.String(length=255), nullable=True),
    sa.Column('status_rca', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('business', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('regdate', sa.String(length=200), nullable=True),
    sa.Column('certificate', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('province', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('cell', sa.String(length=200), nullable=True),
    sa.Column('Activity', sa.String(length=200), nullable=True),
    sa.Column('coop_type', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('started_data', sa.DateTime(), nullable=True),
    sa.Column('starting_share', sa.Integer(), nullable=True),
    sa.Column('share_per_person', sa.String(length=200), nullable=True),
    sa.Column('male_members', sa.String(length=200), nullable=True),
    sa.Column('female_members', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('federations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('certificate', sa.String(length=200), nullable=True),
    sa.Column('reg_date', sa.String(length=200), nullable=True),
    sa.Column('province', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixeddepositaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=200), nullable=True),
    sa.Column('memberName', sa.String(length=200), nullable=True),
    sa.Column('fixedDepositAmount', sa.String(length=200), nullable=True),
    sa.Column('durationInDay', sa.String(length=200), nullable=True),
    sa.Column('fixedDepositInterest', sa.String(length=200), nullable=True),
    sa.Column('maturityDate', sa.String(length=200), nullable=True),
    sa.Column('matureAmount', sa.String(length=200), nullable=True),
    sa.Column('createdBy', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=200), nullable=True),
    sa.Column('loanId', sa.String(length=200), nullable=True),
    sa.Column('memberName', sa.String(length=200), nullable=True),
    sa.Column('lastInstallmentPay', sa.String(length=200), nullable=True),
    sa.Column('lastInstallmentPayDate', sa.String(length=200), nullable=True),
    sa.Column('cashOrCheque', sa.String(length=200), nullable=True),
    sa.Column('payLoanInstallment', sa.String(length=200), nullable=True),
    sa.Column('balance', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('remarksIfAny', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('starting_date', sa.String(length=200), nullable=True),
    sa.Column('ending_date', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_coopthevigi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.Integer(), nullable=True),
    sa.Column('Amazina', sa.String(length=255), nullable=True),
    sa.Column('Ibiro', sa.Float(), nullable=True),
    sa.Column('Igiciro', sa.Float(), nullable=True),
    sa.Column('Quality', sa.Float(), nullable=True),
    sa.Column('Avance', sa.Float(), nullable=True),
    sa.Column('Musa', sa.Integer(), nullable=True),
    sa.Column('Asigaye', sa.Float(), nullable=True),
    sa.Column('Telephone', sa.String(length=255), nullable=True),
    sa.Column('Status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankAccountNumber', sa.String(length=200), nullable=True),
    sa.Column('memberName', sa.String(length=200), nullable=True),
    sa.Column('accountType', sa.String(length=200), nullable=True),
    sa.Column('depositOrWithdraw', sa.String(length=200), nullable=True),
    sa.Column('cashOrCheque', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('balance', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=60), nullable=True),
    sa.Column('asset_location', sa.String(length=60), nullable=True),
    sa.Column('asset_value', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccountName', sa.String(length=200), nullable=True),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('amatsinda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailaa', sa.String(length=200), nullable=True),
    sa.Column('firstNameaa', sa.String(length=200), nullable=True),
    sa.Column('secondNameaa', sa.String(length=200), nullable=True),
    sa.Column('othersaa', sa.String(length=200), nullable=True),
    sa.Column('Districtaa', sa.String(length=200), nullable=True),
    sa.Column('Sectoraa', sa.String(length=200), nullable=True),
    sa.Column('Cellaa', sa.String(length=200), nullable=True),
    sa.Column('nIdaa', sa.String(length=200), nullable=True),
    sa.Column('entryDateaa', sa.String(length=200), nullable=True),
    sa.Column('shareaa', sa.String(length=200), nullable=True),
    sa.Column('exitDateaa', sa.String(length=200), nullable=True),
    sa.Column('umuzunguraaa', sa.String(length=200), nullable=True),
    sa.Column('umukonoaa', sa.String(length=200), nullable=True),
    sa.Column('genderaa', sa.String(length=200), nullable=True),
    sa.Column('dobaa', sa.String(length=200), nullable=True),
    sa.Column('phoneaa', sa.String(length=200), nullable=True),
    sa.Column('Amashuriaa', sa.String(length=200), nullable=True),
    sa.Column('Ubumugaaa', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('applytrainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namea', sa.String(length=200), nullable=True),
    sa.Column('abouta', sa.String(length=200), nullable=True),
    sa.Column('descriptiona', sa.String(length=200), nullable=True),
    sa.Column('datea', sa.String(length=200), nullable=True),
    sa.Column('is_activea', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arc_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nimero', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('izina_ribanza', sa.String(length=255), nullable=True),
    sa.Column('izina_rikurikira', sa.String(length=255), nullable=True),
    sa.Column('ubwoko', sa.String(length=255), nullable=True),
    sa.Column('ingano_kg', sa.String(length=255), nullable=True),
    sa.Column('igiciro_kg', sa.String(length=255), nullable=True),
    sa.Column('igiciro_cya_byose', sa.String(length=255), nullable=True),
    sa.Column('umusanzu_koperative', sa.String(length=255), nullable=True),
    sa.Column('ayishyurwa_umuhinzi', sa.String(length=255), nullable=True),
    sa.Column('telefoni', sa.String(length=255), nullable=True),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('assetsaccounting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(length=200), nullable=True),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('Account', sa.String(length=200), nullable=True),
    sa.Column('Amount', sa.String(length=200), nullable=True),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bankaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=200), nullable=True),
    sa.Column('memberName', sa.String(length=200), nullable=True),
    sa.Column('bankAccountNumber', sa.String(length=200), nullable=True),
    sa.Column('accountType', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('Date', sa.String(length=200), nullable=True),
    sa.Column('Amount', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('nid', sa.String(length=60), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('sex', sa.String(length=60), nullable=True),
    sa.Column('yob', sa.String(length=60), nullable=True),
    sa.Column('committee', sa.String(length=60), nullable=True),
    sa.Column('position', sa.String(length=60), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('telephone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('monthly_net_salary', sa.String(length=60), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('ms_from', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('to', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('stakeholders', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.String(length=200), nullable=True),
    sa.Column('background', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=True),
    sa.Column('Date', sa.String(length=200), nullable=True),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('Account', sa.String(length=200), nullable=True),
    sa.Column('Amount', sa.String(length=200), nullable=True),
    sa.Column('Desciption', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('expensecategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccountName', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('Description', sa.String(length=200), nullable=True),
    sa.Column('Amount', sa.String(length=200), nullable=True),
    sa.Column('startingDate', sa.String(length=200), nullable=True),
    sa.Column('endingDate', sa.String(length=200), nullable=True),
    sa.Column('paidMembers', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('howtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('labels', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('steps', sa.String(length=200), nullable=True),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ibitabobyabanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('igikorwa', sa.String(length=200), nullable=True),
    sa.Column('debit', sa.String(length=200), nullable=True),
    sa.Column('credit', sa.String(length=200), nullable=True),
    sa.Column('solde', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inamaubuyobozi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('stakeholders', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.String(length=200), nullable=True),
    sa.Column('background', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=True),
    sa.Column('Date', sa.String(length=200), nullable=True),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('Account', sa.String(length=200), nullable=True),
    sa.Column('Amount', sa.String(length=200), nullable=True),
    sa.Column('Desciption', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('incomecategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('intekorusange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status1', sa.String(length=200), nullable=True),
    sa.Column('decision1', sa.String(length=200), nullable=True),
    sa.Column('owner1', sa.String(length=200), nullable=True),
    sa.Column('stakeholders1', sa.String(length=200), nullable=True),
    sa.Column('due_date1', sa.String(length=200), nullable=True),
    sa.Column('background1', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('isanduku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('expense', sa.Integer(), nullable=True),
    sa.Column('remain', sa.String(length=200), nullable=True),
    sa.Column('done_by', sa.String(length=200), nullable=True),
    sa.Column('done_to', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('labels', sa.String(length=200), nullable=True),
    sa.Column('sharewith', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=200), nullable=True),
    sa.Column('memberName', sa.String(length=200), nullable=True),
    sa.Column('introducer1Id', sa.String(length=200), nullable=True),
    sa.Column('introducer1Name', sa.String(length=200), nullable=True),
    sa.Column('introducer1BankAccountBalance', sa.String(length=200), nullable=True),
    sa.Column('introducer1Share', sa.String(length=200), nullable=True),
    sa.Column('introducer2Id', sa.String(length=200), nullable=True),
    sa.Column('introducer2Name', sa.String(length=200), nullable=True),
    sa.Column('introducer2BankAccountBalance', sa.String(length=200), nullable=True),
    sa.Column('introducer2Share', sa.String(length=200), nullable=True),
    sa.Column('loanAmount', sa.String(length=200), nullable=True),
    sa.Column('interestRate', sa.String(length=200), nullable=True),
    sa.Column('durationInDay', sa.String(length=200), nullable=True),
    sa.Column('remarksIfAny', sa.String(length=200), nullable=True),
    sa.Column('loanType', sa.String(length=200), nullable=True),
    sa.Column('totalLoanWithInterest', sa.String(length=200), nullable=True),
    sa.Column('activedBy', sa.String(length=200), nullable=True),
    sa.Column('loanIssueDate', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('done_by', sa.String(length=200), nullable=True),
    sa.Column('done_from', sa.String(length=200), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('done_time', sa.String(length=200), nullable=True),
    sa.Column('done_to', sa.String(length=200), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ordes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.String(length=200), nullable=True),
    sa.Column('in_date', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.String(length=200), nullable=True),
    sa.Column('in_date', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rukomatanyo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariki_byakozwe', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('piyesi', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('nid', sa.String(length=60), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('sex', sa.String(length=60), nullable=True),
    sa.Column('yob', sa.String(length=60), nullable=True),
    sa.Column('position', sa.String(length=60), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('telephone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('monthly_net_salary', sa.String(length=60), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('trainer', sa.String(length=200), nullable=True),
    sa.Column('about', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubugenzuzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('stakeholders', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.String(length=200), nullable=True),
    sa.Column('background', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ubwisazures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AssetDescription', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('YearOfPurchase', sa.String(length=200), nullable=True),
    sa.Column('SalvageValue', sa.Integer(), nullable=True),
    sa.Column('UsefulLife', sa.String(length=200), nullable=True),
    sa.Column('Method', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('unions',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('sno', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('certificate', sa.String(length=200), nullable=True),
    sa.Column('reg_date', sa.String(length=200), nullable=True),
    sa.Column('province', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.Column('federation_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('InguzanyoZatanzwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('cooperative_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_coop_admin', sa.Boolean(), nullable=True),
    sa.Column('is_overall', sa.Boolean(), nullable=True),
    sa.Column('is_invited', sa.Boolean(), nullable=True),
    sa.Column('is_union', sa.Boolean(), nullable=True),
    sa.Column('is_ferwacotamo', sa.Boolean(), nullable=True),
    sa.Column('is_confederation', sa.Boolean(), nullable=True),
    sa.Column('is_rca', sa.Boolean(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('is_accountant', sa.Boolean(), nullable=True),
    sa.Column('is_production_manager', sa.Boolean(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.Column('invited_by', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_phone_number'), 'employees', ['phone_number'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=False)
    op.create_table('ibicuruzwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibindiRukomatanya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibiramba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ikoreshwaRyimari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inguzanyozabandi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inkunga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isandukunshya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('izina_ribanza', sa.String(length=200), nullable=True),
    sa.Column('izina_rikurikira', sa.String(length=200), nullable=True),
    sa.Column('Ayandi', sa.String(length=200), nullable=True),
    sa.Column('zone', sa.String(length=200), nullable=True),
    sa.Column('itsinda', sa.String(length=200), nullable=True),
    sa.Column('Igitsina', sa.String(length=200), nullable=True),
    sa.Column('Indangamuntu', sa.Integer(), nullable=True),
    sa.Column('tariki_yavukiye', sa.String(length=200), nullable=True),
    sa.Column('Intara', sa.String(length=200), nullable=True),
    sa.Column('Akarere', sa.String(length=200), nullable=True),
    sa.Column('Umurenge', sa.String(length=200), nullable=True),
    sa.Column('Akagari', sa.String(length=200), nullable=True),
    sa.Column('Umudugudu', sa.String(length=200), nullable=True),
    sa.Column('tariki_yinjiriye', sa.String(length=200), nullable=True),
    sa.Column('umugabane', sa.Integer(), nullable=True),
    sa.Column('Umukono', sa.String(length=200), nullable=True),
    sa.Column('nomero_telephone', sa.String(length=200), nullable=True),
    sa.Column('Amashuri', sa.String(length=200), nullable=True),
    sa.Column('Ubumuga', sa.String(length=200), nullable=True),
    sa.Column('Arubatse', sa.String(length=200), nullable=True),
    sa.Column('umubare_abana', sa.String(length=200), nullable=True),
    sa.Column('icyiciro_ubudehe', sa.String(length=200), nullable=True),
    sa.Column('Ubwishingizi', sa.String(length=200), nullable=True),
    sa.Column('akazi_akora_muri_koperative', sa.String(length=200), nullable=True),
    sa.Column('akazi_akora_ahandi', sa.String(length=200), nullable=True),
    sa.Column('ubuso_ahingaho', sa.String(length=200), nullable=True),
    sa.Column('ubwoko_igihingwa', sa.String(length=200), nullable=True),
    sa.Column('ubuso_ahingaho_ibindi', sa.String(length=200), nullable=True),
    sa.Column('ubwoko_igihingwa_kindi', sa.String(length=200), nullable=True),
    sa.Column('ubuso_budakoreshwa', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('bank', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ububiko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umugabaneShingiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('izina', sa.String(length=100), nullable=True),
    sa.Column('ubusobanuro', sa.String(length=200), nullable=True),
    sa.Column('impamvu', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CRMs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact_type', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('contributionFor', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('coopMemberBankAccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberName', sa.String(length=100), nullable=True),
    sa.Column('bankName', sa.String(length=50), nullable=True),
    sa.Column('bankAccountNumber', sa.String(length=50), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bankAccountNumber'),
    sa.UniqueConstraint('bankName')
    )
    op.create_table('ibihano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AmandeC', sa.String(length=200), nullable=True),
    sa.Column('AmandeApII', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibindi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ImifukaQuantity', sa.Integer(), nullable=True),
    sa.Column('ImifukaAmount', sa.Integer(), nullable=True),
    sa.Column('rpf', sa.Integer(), nullable=True),
    sa.Column('ejo_heza', sa.Integer(), nullable=True),
    sa.Column('mituelle_amount', sa.Integer(), nullable=True),
    sa.Column('carnet', sa.Integer(), nullable=True),
    sa.Column('avance', sa.Integer(), nullable=True),
    sa.Column('loan', sa.Integer(), nullable=True),
    sa.Column('UmuceriGrade', sa.String(length=200), nullable=True),
    sa.Column('UmuceriQuantity', sa.Integer(), nullable=True),
    sa.Column('UmuceriAmountGrade', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibirarane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('IdeniAmount', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('Briquette', sa.Integer(), nullable=True),
    sa.Column('BriquettePerUnity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibyakoreshejwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazina', sa.String(length=200), nullable=True),
    sa.Column('deamAndSup', sa.Integer(), nullable=True),
    sa.Column('ibihanoCoop', sa.Integer(), nullable=True),
    sa.Column('APKSAMAKIbihano', sa.Integer(), nullable=True),
    sa.Column('ibiraraneNPKandUREA', sa.Integer(), nullable=True),
    sa.Column('umusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('kwishyuraItsinda', sa.Integer(), nullable=True),
    sa.Column('sheeting', sa.Integer(), nullable=True),
    sa.Column('PandS', sa.Integer(), nullable=True),
    sa.Column('ibyoYagurijwe', sa.Integer(), nullable=True),
    sa.Column('ibindiYasbwe', sa.Integer(), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inyongeramusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('Briquette', sa.Integer(), nullable=True),
    sa.Column('BriquettePerUnity', sa.Integer(), nullable=True),
    sa.Column('Cypemetrine', sa.Float(), nullable=True),
    sa.Column('Beam', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('Redevance', sa.Float(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itsindamember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('itsinda_id', sa.Integer(), nullable=True),
    sa.Column('member_firstname', sa.String(length=200), nullable=True),
    sa.Column('member_secondname', sa.String(length=200), nullable=True),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['itsinda_id'], ['amatsinda.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('plate', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('owner_tel', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_school', sa.String(length=200), nullable=True),
    sa.Column('secondary_school', sa.String(length=200), nullable=True),
    sa.Column('university_school', sa.String(length=200), nullable=True),
    sa.Column('vocational_school', sa.String(length=200), nullable=True),
    sa.Column('exp1', sa.String(length=200), nullable=True),
    sa.Column('exp2', sa.String(length=200), nullable=True),
    sa.Column('exp3', sa.String(length=200), nullable=True),
    sa.Column('strn1', sa.String(length=200), nullable=True),
    sa.Column('strn2', sa.String(length=200), nullable=True),
    sa.Column('strn3', sa.String(length=200), nullable=True),
    sa.Column('car1', sa.String(length=200), nullable=True),
    sa.Column('car2', sa.String(length=200), nullable=True),
    sa.Column('car3', sa.String(length=200), nullable=True),
    sa.Column('inter1', sa.String(length=200), nullable=True),
    sa.Column('inter2', sa.String(length=200), nullable=True),
    sa.Column('inter3', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusanzu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UmusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('UmusanzuCoop', sa.Integer(), nullable=True),
    sa.Column('Umugabane', sa.Integer(), nullable=True),
    sa.Column('Ikigega', sa.Integer(), nullable=True),
    sa.Column('KuzibaIcyuho', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazina', sa.String(length=100), nullable=True),
    sa.Column('resi', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('umusaruro', sa.Integer(), nullable=True),
    sa.Column('umuceriYagurijwe', sa.Integer(), nullable=True),
    sa.Column('umuceriWoKurya', sa.Float(), nullable=True),
    sa.Column('umuceriWoKugurisha', sa.Integer(), nullable=True),
    sa.Column('igiciroCyaKimwe', sa.Integer(), nullable=True),
    sa.Column('umusanzu', sa.Integer(), nullable=True),
    sa.Column('amafarangaYose', sa.Integer(), nullable=True),
    sa.Column('amafarangaYoGutonoza', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('umwakaWisarura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusarurob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RiceType', sa.String(length=100), nullable=True),
    sa.Column('UmusaruroGrade', sa.String(length=200), nullable=True),
    sa.Column('RicePrice', sa.Float(), nullable=True),
    sa.Column('RiceAmount', sa.Integer(), nullable=True),
    sa.Column('UwoAsigaranye', sa.Float(), nullable=True),
    sa.Column('UwoKugurisha', sa.Integer(), nullable=True),
    sa.Column('GutonozaAmount', sa.Integer(), nullable=True),
    sa.Column('AmafarangaUmusaruro1', sa.Integer(), nullable=True),
    sa.Column('Asigaye', sa.Float(), nullable=True),
    sa.Column('Ibikase', sa.Integer(), nullable=True),
    sa.Column('Ibisigaye', sa.Integer(), nullable=True),
    sa.Column('Musa', sa.Integer(), nullable=True),
    sa.Column('Carnet', sa.Integer(), nullable=True),
    sa.Column('Avance', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abishyuwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_payed', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=200), nullable=True),
    sa.Column('ibiro', sa.Float(), nullable=True),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.Column('umusaruro_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['umusaruro_id'], ['umusarurob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abishyuwe')
    op.drop_table('umusarurob')
    op.drop_table('umusaruro')
    op.drop_table('umusanzu')
    op.drop_table('profiles')
    op.drop_table('motos')
    op.drop_table('itsindamember')
    op.drop_table('inyongeramusaruro')
    op.drop_table('ibyakoreshejwe')
    op.drop_table('ibirarane')
    op.drop_table('ibindi')
    op.drop_table('ibihano')
    op.drop_table('coopMemberBankAccounts')
    op.drop_table('contributions')
    op.drop_table('CRMs')
    op.drop_table('zones')
    op.drop_table('umugabaneShingiro')
    op.drop_table('ububiko')
    op.drop_table('members')
    op.drop_table('isandukunshya')
    op.drop_table('inkunga')
    op.drop_table('inguzanyozabandi')
    op.drop_table('ikoreshwaRyimari')
    op.drop_table('ibiramba')
    op.drop_table('ibindiRukomatanya')
    op.drop_table('ibicuruzwa')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('bank')
    op.drop_table('InguzanyoZatanzwe')
    op.drop_table('unions')
    op.drop_table('ubwisazures')
    op.drop_table('ubugenzuzi')
    op.drop_table('trainings')
    op.drop_table('staffs')
    op.drop_table('rukomatanyo')
    op.drop_table('roles')
    op.drop_table('reports')
    op.drop_table('products')
    op.drop_table('post')
    op.drop_table('ordes')
    op.drop_table('notifications')
    op.drop_table('loans')
    op.drop_table('links')
    op.drop_table('isanduku')
    op.drop_table('intekorusange')
    op.drop_table('incomecategory')
    op.drop_table('income')
    op.drop_table('inamaubuyobozi')
    op.drop_table('ibitabobyabanks')
    op.drop_table('howtos')
    op.drop_table('goals')
    op.drop_table('files')
    op.drop_table('expensecategory')
    op.drop_table('expense')
    op.drop_table('decisions')
    op.drop_table('communications')
    op.drop_table('committees')
    op.drop_table('budget')
    op.drop_table('bankaccounts')
    op.drop_table('assetsaccounting')
    op.drop_table('arc_stock')
    op.drop_table('applytrainings')
    op.drop_table('applications')
    op.drop_table('amatsinda')
    op.drop_table('activities')
    op.drop_table('account')
    op.drop_table('Assets')
    op.drop_table('transactions')
    op.drop_table('temp_coopthevigi')
    op.drop_table('projects')
    op.drop_table('payments')
    op.drop_table('installments')
    op.drop_table('fixeddepositaccounts')
    op.drop_table('federations')
    op.drop_table('departments')
    op.drop_table('cooperatives')
    op.drop_table('clients')
    op.drop_table('category')
    op.drop_table('arc_cooperatives')
    # ### end Alembic commands ###
