"""empty message

Revision ID: 23d7aff2651a
Revises: b0e89c23feda
Create Date: 2020-01-08 10:39:25.413127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d7aff2651a'
down_revision = 'b0e89c23feda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('bank', sa.String(length=200), nullable=True))
    op.add_column('members', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('umusarurob', sa.Column('RicePrice', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusarurob', 'RicePrice')
    op.drop_column('members', 'email')
    op.drop_column('members', 'bank')
    # ### end Alembic commands ###
