"""empty message

Revision ID: 25d8b88daf1c
Revises: 3c7e00abf0e3
Create Date: 2019-01-31 16:46:56.133490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d8b88daf1c'
down_revision = '3c7e00abf0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itsindamember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('itsinda_id', sa.Integer(), nullable=True),
    sa.Column('member_firstname', sa.String(length=200), nullable=True),
    sa.Column('member_secondname', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['itsinda_id'], ['amatsinda.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itsindamember')
    # ### end Alembic commands ###
