"""empty message

Revision ID: 29369794c1da
Revises: 
Create Date: 2020-01-20 12:55:46.292181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29369794c1da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibindi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ImifukaQuantity', sa.Integer(), nullable=True),
    sa.Column('ImifukaAmount', sa.Integer(), nullable=True),
    sa.Column('rpf', sa.Integer(), nullable=True),
    sa.Column('ejo_heza', sa.Integer(), nullable=True),
    sa.Column('mituelle_amount', sa.Integer(), nullable=True),
    sa.Column('carnet', sa.Integer(), nullable=True),
    sa.Column('avance', sa.Integer(), nullable=True),
    sa.Column('loan', sa.Integer(), nullable=True),
    sa.Column('UmuceriGrade', sa.String(length=200), nullable=True),
    sa.Column('UmuceriQuantity', sa.Integer(), nullable=True),
    sa.Column('UmuceriAmountGrade', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibindi')
    # ### end Alembic commands ###
