"""empty message

Revision ID: 2e6c46944e4d
Revises: c1eb8dc85fab
Create Date: 2020-01-09 14:08:59.163771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6c46944e4d'
down_revision = 'c1eb8dc85fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Category', table_name='budgetcategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('Category', 'budgetcategory', ['Category'], unique=True)
    # ### end Alembic commands ###
