"""empty message

Revision ID: 31de13f10f8b
Revises: 5fcec3886685
Create Date: 2019-11-13 16:14:20.460282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31de13f10f8b'
down_revision = '5fcec3886685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'members', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='unique')
    # ### end Alembic commands ###
