"""empty message

Revision ID: 323fcffb3d9b
Revises: 
Create Date: 2018-11-13 13:43:47.734549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '323fcffb3d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inyongeramusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('Briquette', sa.Integer(), nullable=True),
    sa.Column('BriquettePerUnity', sa.Integer(), nullable=True),
    sa.Column('Cypemetrine', sa.Float(), nullable=True),
    sa.Column('Beam', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('Redevance', sa.Float(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('umwakaWisarura', sa.String(length=50), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('umusarurob', 'Quantity')
    op.add_column('unions', sa.Column('federation_id', sa.Integer(), nullable=True))
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.create_foreign_key(None, 'unions', 'federations', ['federation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unions', type_='foreignkey')
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('unions', 'federation_id')
    op.add_column('umusarurob', sa.Column('Quantity', mysql.FLOAT(), nullable=True))
    op.drop_table('inyongeramusaruro')
    # ### end Alembic commands ###
