"""empty message

Revision ID: 3a82e4b5b30f
Revises: 3cbd5c20c077
Create Date: 2019-12-02 15:10:18.280134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a82e4b5b30f'
down_revision = '3cbd5c20c077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusaruro', sa.Column('umwakaWisarura', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusaruro', 'umwakaWisarura')
    # ### end Alembic commands ###
