"""empty message

Revision ID: 3ae711ff0540
Revises: 969e0b507399
Create Date: 2020-07-23 15:05:45.111632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ae711ff0540'
down_revision = '969e0b507399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_coopthevigi', 'Code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('temp_coopthevigi', 'Sector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_coopthevigi', sa.Column('Sector', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('temp_coopthevigi', 'Code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
