"""empty message

Revision ID: 3c7e00abf0e3
Revises: cf0d2c1b4256
Create Date: 2019-01-31 05:38:12.221148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7e00abf0e3'
down_revision = 'cf0d2c1b4256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amatsinda', sa.Column('department_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'amatsinda', 'departments', ['department_id'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'amatsinda', type_='foreignkey')
    op.drop_column('amatsinda', 'department_id')
    # ### end Alembic commands ###
