"""empty message

Revision ID: 3cbd5c20c077
Revises: 8565b498897b
Create Date: 2019-12-02 15:09:52.107254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cbd5c20c077'
down_revision = '8565b498897b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusaruro', 'umwakaWisarura')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusaruro', sa.Column('umwakaWisarura', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
