"""empty message

Revision ID: 4642325dbd7c
Revises: ea8216134708
Create Date: 2019-02-03 17:30:45.375386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4642325dbd7c'
down_revision = 'ea8216134708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ikoreshwaRyimari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ikoreshwaRyimari')
    # ### end Alembic commands ###
