"""empty message

Revision ID: 537bc5bbe0aa
Revises: 3240af42ea2d
Create Date: 2019-02-25 11:53:24.840968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537bc5bbe0aa'
down_revision = '3240af42ea2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ubwisazures', sa.Column('Method', sa.String(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('SalvageValue', sa.Integer(), nullable=True))
    op.add_column('ubwisazures', sa.Column('UsefulLife', sa.String(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('YearOfPurchase', sa.String(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ubwisazures', 'cost')
    op.drop_column('ubwisazures', 'YearOfPurchase')
    op.drop_column('ubwisazures', 'UsefulLife')
    op.drop_column('ubwisazures', 'SalvageValue')
    op.drop_column('ubwisazures', 'Method')
    # ### end Alembic commands ###
