"""empty message

Revision ID: 57927e1c38e8
Revises: eceb0572f264
Create Date: 2019-02-25 09:31:32.348560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57927e1c38e8'
down_revision = 'eceb0572f264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubwisazures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AssetDescription', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.String(length=200), nullable=True),
    sa.Column('YearOfPurchase', sa.String(length=200), nullable=True),
    sa.Column('SalvageValue', sa.String(length=200), nullable=True),
    sa.Column('UsefulLife', sa.String(length=200), nullable=True),
    sa.Column('Method', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('ubwisazure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubwisazure',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('AssetDescription', sa.DATE(), nullable=True),
    sa.Column('cost', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YearOfPurchase', sa.DATE(), nullable=True),
    sa.Column('SalvageValue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('UsefulLife', sa.DATE(), nullable=True),
    sa.Column('Method', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('department_id', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.email'], name=u'ubwisazure_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ubwisazures')
    # ### end Alembic commands ###
