"""empty message

Revision ID: 598fb8769ad2
Revises: f77624abd8d3
Create Date: 2018-11-23 10:50:42.170288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '598fb8769ad2'
down_revision = 'f77624abd8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibirarane', sa.Column('Briquette', sa.Integer(), nullable=True))
    op.add_column('ibirarane', sa.Column('BriquettePerUnity', sa.Integer(), nullable=True))
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('ibirarane', 'BriquettePerUnity')
    op.drop_column('ibirarane', 'Briquette')
    # ### end Alembic commands ###
