"""empty message

Revision ID: 59e26acadbec
Revises: f51a7b1793d7
Create Date: 2020-04-04 15:31:45.472930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e26acadbec'
down_revision = 'f51a7b1793d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_super_user')
    # ### end Alembic commands ###
