"""empty message

Revision ID: 5fcec3886685
Revises: c6440a82b8d0
Create Date: 2019-11-13 16:12:08.001166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcec3886685'
down_revision = 'c6440a82b8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'members', ['id'], unique=True)
    # ### end Alembic commands ###
