"""empty message

Revision ID: 656dac64dbea
Revises: 5536d71349fb
Create Date: 2019-03-20 16:16:23.666578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656dac64dbea'
down_revision = '5536d71349fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abishyuwe', sa.Column('member_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abishyuwe', 'member_name')
    # ### end Alembic commands ###
