"""empty message

Revision ID: 68589004c420
Revises: 9ed5ce68d482
Create Date: 2019-02-22 16:43:50.500079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68589004c420'
down_revision = '9ed5ce68d482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubwisazure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AssetDescription', sa.Date(), nullable=True),
    sa.Column('cost', sa.String(length=200), nullable=True),
    sa.Column('YearOfPurchase', sa.Date(), nullable=True),
    sa.Column('SalvageValue', sa.String(length=200), nullable=True),
    sa.Column('UsefulLife', sa.Date(), nullable=True),
    sa.Column('Method', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubwisazure')
    # ### end Alembic commands ###
