"""empty message

Revision ID: 685fa8c7b147
Revises: cee35164b6bb
Create Date: 2019-02-18 11:36:05.966392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685fa8c7b147'
down_revision = 'cee35164b6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rukomatanyo', sa.Column('department_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'rukomatanyo', 'departments', ['department_id'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rukomatanyo', type_='foreignkey')
    op.drop_column('rukomatanyo', 'department_id')
    # ### end Alembic commands ###
