"""empty message

Revision ID: 6a7c0e9dcf12
Revises: cfeba487c037
Create Date: 2019-02-03 14:00:46.374657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7c0e9dcf12'
down_revision = 'cfeba487c037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isandukunshya', sa.Column('department_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'isandukunshya', 'departments', ['department_id'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'isandukunshya', type_='foreignkey')
    op.drop_column('isandukunshya', 'department_id')
    # ### end Alembic commands ###
