"""empty message

Revision ID: 6ae370db940f
Revises: 8476bccc07c9
Create Date: 2019-02-05 08:45:52.457988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae370db940f'
down_revision = '8476bccc07c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'itsindamember', ['member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itsindamember', type_='unique')
    # ### end Alembic commands ###
