"""empty message

Revision ID: 6c76b15e29b8
Revises: 57927e1c38e8
Create Date: 2019-02-25 09:58:42.883648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c76b15e29b8'
down_revision = '57927e1c38e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ubwisazures', 'YearOfPurchase')
    op.drop_column('ubwisazures', 'cost')
    op.drop_column('ubwisazures', 'UsefulLife')
    op.drop_column('ubwisazures', 'SalvageValue')
    op.drop_column('ubwisazures', 'Method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ubwisazures', sa.Column('Method', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('SalvageValue', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('UsefulLife', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('cost', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ubwisazures', sa.Column('YearOfPurchase', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
