"""empty message

Revision ID: 6e895bed9114
Revises: 
Create Date: 2019-02-12 20:20:29.534449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e895bed9114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itsindamember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('itsinda_id', sa.Integer(), nullable=True),
    sa.Column('member_firstname', sa.String(length=200), nullable=True),
    sa.Column('member_secondname', sa.String(length=200), nullable=True),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['itsinda_id'], ['amatsinda.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itsindamember')
    # ### end Alembic commands ###
