"""empty message

Revision ID: 703b38cc23d1
Revises: fcaba37a8498
Create Date: 2019-01-03 13:08:14.918354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703b38cc23d1'
down_revision = 'fcaba37a8498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('nid', sa.String(length=60), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('sex', sa.String(length=60), nullable=True),
    sa.Column('yob', sa.String(length=60), nullable=True),
    sa.Column('committee', sa.String(length=60), nullable=True),
    sa.Column('position', sa.String(length=60), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('telephone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('monthly_net_salary', sa.String(length=60), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committees')
    # ### end Alembic commands ###
