"""empty message

Revision ID: 8565b498897b
Revises: 
Create Date: 2019-11-30 15:53:59.794225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8565b498897b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.add_column('members', sa.Column('umugabane', sa.String(length=200), nullable=True))
    op.drop_column('members', 'umugabane_ukwezi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('umugabane_ukwezi', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('members', 'umugabane')
    op.create_table('userinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('secondname', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
