"""empty message

Revision ID: 89bb88418847
Revises: 
Create Date: 2019-02-14 08:50:20.357343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89bb88418847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InguzanyoZatanzwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amatsinda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibicuruzwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibindiRukomatanya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibiramba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ikoreshwaRyimari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inguzanyozabandi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inkunga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isandukunshya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ububiko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umugabaneShingiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('izina', sa.String(length=100), nullable=True),
    sa.Column('ubusobanuro', sa.String(length=200), nullable=True),
    sa.Column('impamvu', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itsindamember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('itsinda_id', sa.Integer(), nullable=True),
    sa.Column('member_firstname', sa.String(length=200), nullable=True),
    sa.Column('member_secondname', sa.String(length=200), nullable=True),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['itsinda_id'], ['amatsinda.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'employees', sa.Column('is_ferwacotamo', sa.Boolean(), nullable=True))
    op.drop_column(u'employees', 'is_rab')
    op.drop_column(u'employees', 'is_federation')
    op.drop_column(u'employees', 'is_production_manager')
    op.drop_column(u'employees', 'is_manager')
    op.drop_column(u'employees', 'is_stock_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'employees', sa.Column('is_stock_manager', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'employees', sa.Column('is_manager', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'employees', sa.Column('is_production_manager', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'employees', sa.Column('is_federation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'employees', sa.Column('is_rab', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column(u'employees', 'is_ferwacotamo')
    op.drop_table('itsindamember')
    op.drop_table('zones')
    op.drop_table('umugabaneShingiro')
    op.drop_table('ububiko')
    op.drop_table('isandukunshya')
    op.drop_table('inkunga')
    op.drop_table('inguzanyozabandi')
    op.drop_table('ikoreshwaRyimari')
    op.drop_table('ibiramba')
    op.drop_table('ibindiRukomatanya')
    op.drop_table('ibicuruzwa')
    op.drop_table('bank')
    op.drop_table('amatsinda')
    op.drop_table('InguzanyoZatanzwe')
    # ### end Alembic commands ###
