"""empty message

Revision ID: 8a73ae434bf3
Revises: 0267277282bf
Create Date: 2019-03-20 16:34:11.597627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a73ae434bf3'
down_revision = '0267277282bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abishyuwe', sa.Column('umusaruro_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'abishyuwe', 'umusarurob', ['umusaruro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abishyuwe', type_='foreignkey')
    op.drop_column('abishyuwe', 'umusaruro_id')
    # ### end Alembic commands ###
