"""empty message

Revision ID: 8d47a986ce9e
Revises: dbdb4d972aeb
Create Date: 2020-01-08 11:44:03.108271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d47a986ce9e'
down_revision = 'dbdb4d972aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('ubuso_ahingaho', sa.String(length=200), nullable=True))
    op.add_column('members', sa.Column('ubwoko_igihingwa', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'ubwoko_igihingwa')
    op.drop_column('members', 'ubuso_ahingaho')
    # ### end Alembic commands ###
