"""empty message

Revision ID: 969e0b507399
Revises: 9bee23a31801
Create Date: 2020-07-23 08:26:54.669167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '969e0b507399'
down_revision = '9bee23a31801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_coopthevigi', 'Amazina',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('temp_coopthevigi', 'Ibiro',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('temp_coopthevigi', 'Igiciro',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('temp_coopthevigi', 'Status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('temp_coopthevigi', 'Telephone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'temp_coopthevigi', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_coopthevigi', type_='unique')
    op.alter_column('temp_coopthevigi', 'Telephone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('temp_coopthevigi', 'Status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('temp_coopthevigi', 'Igiciro',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('temp_coopthevigi', 'Ibiro',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('temp_coopthevigi', 'Amazina',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
