"""empty message

Revision ID: 99de89dedde9
Revises: 2e6c46944e4d
Create Date: 2020-01-09 16:44:11.823942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99de89dedde9'
down_revision = '2e6c46944e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assetcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(length=200), nullable=True),
    sa.Column('cooperative_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assetcategory')
    # ### end Alembic commands ###
