"""empty message

Revision ID: 9bee23a31801
Revises: 
Create Date: 2020-07-22 23:07:37.843572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bee23a31801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_coopthevigi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Amazina', sa.String(length=255), nullable=True),
    sa.Column('Ibiro', sa.Integer(), nullable=True),
    sa.Column('Igiciro', sa.Integer(), nullable=True),
    sa.Column('Telephone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_coopthevigi')
    # ### end Alembic commands ###
