"""empty message

Revision ID: a28816b8ad8c
Revises: 59e26acadbec
Create Date: 2020-04-04 18:33:28.972490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28816b8ad8c'
down_revision = '59e26acadbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arc_cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('cooperative_name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('reg_date', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('male_members', sa.String(length=255), nullable=True),
    sa.Column('female_members', sa.String(length=255), nullable=True),
    sa.Column('total_members', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('share_person', sa.String(length=255), nullable=True),
    sa.Column('president_and_contact', sa.String(length=255), nullable=True),
    sa.Column('status_rca', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arc_cooperatives')
    # ### end Alembic commands ###
