"""empty message

Revision ID: b0e89c23feda
Revises: beed3b065a61
Create Date: 2019-12-03 10:20:39.531285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e89c23feda'
down_revision = 'beed3b065a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusaruro', sa.Column('umwakaWisarura', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusaruro', 'umwakaWisarura')
    # ### end Alembic commands ###
