"""empty message

Revision ID: b18b0a8066c5
Revises: 580f27ad26b3
Create Date: 2020-02-12 13:04:43.331638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18b0a8066c5'
down_revision = '580f27ad26b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('d_intl_budget', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('d_time_passed', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('date', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('m_budget_used', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('m_expense', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('m_income', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('m_intl_budget', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('m_time_passed', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('q_budget_used', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('q_intl_budget', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('q_time_passed', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('y_budget_used', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('y_expense', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('y_income', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('y_intl_budget', sa.String(length=200), nullable=True))
    op.add_column('archive', sa.Column('y_time_passed', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archive', 'y_time_passed')
    op.drop_column('archive', 'y_intl_budget')
    op.drop_column('archive', 'y_income')
    op.drop_column('archive', 'y_expense')
    op.drop_column('archive', 'y_budget_used')
    op.drop_column('archive', 'q_time_passed')
    op.drop_column('archive', 'q_intl_budget')
    op.drop_column('archive', 'q_budget_used')
    op.drop_column('archive', 'm_time_passed')
    op.drop_column('archive', 'm_intl_budget')
    op.drop_column('archive', 'm_income')
    op.drop_column('archive', 'm_expense')
    op.drop_column('archive', 'm_budget_used')
    op.drop_column('archive', 'date')
    op.drop_column('archive', 'd_time_passed')
    op.drop_column('archive', 'd_intl_budget')
    # ### end Alembic commands ###
