"""empty message

Revision ID: b2ca3515e267
Revises: 
Create Date: 2018-11-13 16:45:55.577454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ca3515e267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibirarane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('IdeniAmount', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('ibirarane')
    # ### end Alembic commands ###
