"""empty message

Revision ID: beaabec4f5ef
Revises: 27e703638f9f
Create Date: 2020-01-18 08:51:43.877044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaabec4f5ef'
down_revision = '27e703638f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusarurob', sa.Column('Ibikase', sa.Integer(), nullable=True))
    op.add_column('umusarurob', sa.Column('Ibisigaye', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusarurob', 'Ibisigaye')
    op.drop_column('umusarurob', 'Ibikase')
    # ### end Alembic commands ###
