"""empty message

Revision ID: beed3b065a61
Revises: cb2ae08b3870
Create Date: 2019-12-03 10:19:41.445586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beed3b065a61'
down_revision = 'cb2ae08b3870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InguzanyoZatanzwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibicuruzwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibindiRukomatanya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibiramba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ikoreshwaRyimari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inguzanyozabandi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inkunga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isandukunshya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=200), nullable=True),
    sa.Column('izina_ribanza', sa.String(length=200), nullable=True),
    sa.Column('izina_rikurikira', sa.String(length=200), nullable=True),
    sa.Column('Ayandi', sa.String(length=200), nullable=True),
    sa.Column('zone', sa.String(length=200), nullable=True),
    sa.Column('itsinda', sa.String(length=200), nullable=True),
    sa.Column('Igitsina', sa.String(length=200), nullable=True),
    sa.Column('Indangamuntu', sa.Integer(), nullable=True),
    sa.Column('tariki_yavukiye', sa.String(length=200), nullable=True),
    sa.Column('Intara', sa.String(length=200), nullable=True),
    sa.Column('Akarere', sa.String(length=200), nullable=True),
    sa.Column('Umurenge', sa.String(length=200), nullable=True),
    sa.Column('Akagari', sa.String(length=200), nullable=True),
    sa.Column('Umudugudu', sa.String(length=200), nullable=True),
    sa.Column('tariki_yinjiriye', sa.String(length=200), nullable=True),
    sa.Column('umugabane', sa.String(length=200), nullable=True),
    sa.Column('Umukono', sa.String(length=200), nullable=True),
    sa.Column('nomero_telephone', sa.String(length=200), nullable=True),
    sa.Column('Amashuri', sa.String(length=200), nullable=True),
    sa.Column('Ubumuga', sa.String(length=200), nullable=True),
    sa.Column('Arubatse', sa.String(length=200), nullable=True),
    sa.Column('umubare_abana', sa.String(length=200), nullable=True),
    sa.Column('icyiciro_ubudehe', sa.String(length=200), nullable=True),
    sa.Column('Ubwishingizi', sa.String(length=200), nullable=True),
    sa.Column('akazi_akora_muri_koperative', sa.String(length=200), nullable=True),
    sa.Column('akazi_akora_ahandi', sa.String(length=200), nullable=True),
    sa.Column('ubuso_ahingaho', sa.String(length=200), nullable=True),
    sa.Column('ubwoko_igihingwa', sa.String(length=200), nullable=True),
    sa.Column('ubuso_ahingaho_ibindi', sa.String(length=200), nullable=True),
    sa.Column('ubwoko_igihingwa_kindi', sa.String(length=200), nullable=True),
    sa.Column('ubuso_budakoreshwa', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ububiko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umugabaneShingiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('izina', sa.String(length=100), nullable=True),
    sa.Column('ubusobanuro', sa.String(length=200), nullable=True),
    sa.Column('impamvu', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('rukomatanyo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['rukomatanyo_id'], ['rukomatanyo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CRMs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact_type', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('contributionFor', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('coopMemberBankAccounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memberName', sa.String(length=100), nullable=True),
    sa.Column('bankName', sa.String(length=50), nullable=True),
    sa.Column('bankAccountNumber', sa.String(length=50), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bankAccountNumber'),
    sa.UniqueConstraint('bankName')
    )
    op.create_table('ibihano',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AmandeC', sa.String(length=200), nullable=True),
    sa.Column('AmandeApII', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibindi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ImifukaQuantity', sa.Integer(), nullable=True),
    sa.Column('ImifukaAmount', sa.Integer(), nullable=True),
    sa.Column('MituelleAmount', sa.Integer(), nullable=True),
    sa.Column('UmuceriGrade', sa.String(length=200), nullable=True),
    sa.Column('UmuceriQuantity', sa.Integer(), nullable=True),
    sa.Column('UmuceriAmountGrade', sa.Integer(), nullable=True),
    sa.Column('Avence', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibirarane',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('IdeniAmount', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('Briquette', sa.Integer(), nullable=True),
    sa.Column('BriquettePerUnity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibyakoreshejwe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amazina', sa.String(length=200), nullable=True),
    sa.Column('deamAndSup', sa.Integer(), nullable=True),
    sa.Column('ibihanoCoop', sa.Integer(), nullable=True),
    sa.Column('APKSAMAKIbihano', sa.Integer(), nullable=True),
    sa.Column('ibiraraneNPKandUREA', sa.Integer(), nullable=True),
    sa.Column('umusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('kwishyuraItsinda', sa.Integer(), nullable=True),
    sa.Column('sheeting', sa.Integer(), nullable=True),
    sa.Column('PandS', sa.Integer(), nullable=True),
    sa.Column('ibyoYagurijwe', sa.Integer(), nullable=True),
    sa.Column('ibindiYasbwe', sa.Integer(), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inyongeramusaruro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NPKkg', sa.Integer(), nullable=True),
    sa.Column('NPKPerUnity', sa.Integer(), nullable=True),
    sa.Column('UREA', sa.Integer(), nullable=True),
    sa.Column('UREAPerUnity', sa.Integer(), nullable=True),
    sa.Column('DAP', sa.Integer(), nullable=True),
    sa.Column('DAPPerUnity', sa.Integer(), nullable=True),
    sa.Column('KCL', sa.Integer(), nullable=True),
    sa.Column('KCLPerUnity', sa.Integer(), nullable=True),
    sa.Column('Briquette', sa.Integer(), nullable=True),
    sa.Column('BriquettePerUnity', sa.Integer(), nullable=True),
    sa.Column('Cypemetrine', sa.Float(), nullable=True),
    sa.Column('Beam', sa.Integer(), nullable=True),
    sa.Column('ImbutoQuantity', sa.Float(), nullable=True),
    sa.Column('ImbutoAmount', sa.Integer(), nullable=True),
    sa.Column('Redevance', sa.Float(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itsindamember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('itsinda_id', sa.Integer(), nullable=True),
    sa.Column('member_firstname', sa.String(length=200), nullable=True),
    sa.Column('member_secondname', sa.String(length=200), nullable=True),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['itsinda_id'], ['amatsinda.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('plate', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('owner_tel', sa.String(length=200), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_school', sa.String(length=200), nullable=True),
    sa.Column('secondary_school', sa.String(length=200), nullable=True),
    sa.Column('university_school', sa.String(length=200), nullable=True),
    sa.Column('vocational_school', sa.String(length=200), nullable=True),
    sa.Column('exp1', sa.String(length=200), nullable=True),
    sa.Column('exp2', sa.String(length=200), nullable=True),
    sa.Column('exp3', sa.String(length=200), nullable=True),
    sa.Column('strn1', sa.String(length=200), nullable=True),
    sa.Column('strn2', sa.String(length=200), nullable=True),
    sa.Column('strn3', sa.String(length=200), nullable=True),
    sa.Column('car1', sa.String(length=200), nullable=True),
    sa.Column('car2', sa.String(length=200), nullable=True),
    sa.Column('car3', sa.String(length=200), nullable=True),
    sa.Column('inter1', sa.String(length=200), nullable=True),
    sa.Column('inter2', sa.String(length=200), nullable=True),
    sa.Column('inter3', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusanzu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UmusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('UmusanzuCoop', sa.Integer(), nullable=True),
    sa.Column('Umugabane', sa.Integer(), nullable=True),
    sa.Column('Ikigega', sa.Integer(), nullable=True),
    sa.Column('KuzibaIcyuho', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusaruro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amazina', sa.String(length=100), nullable=True),
    sa.Column('resi', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('umusaruro', sa.Integer(), nullable=True),
    sa.Column('umuceriYagurijwe', sa.Integer(), nullable=True),
    sa.Column('umuceriWoKurya', sa.Float(), nullable=True),
    sa.Column('umuceriWoKugurisha', sa.Integer(), nullable=True),
    sa.Column('igiciroCyaKimwe', sa.Integer(), nullable=True),
    sa.Column('umusanzu', sa.Integer(), nullable=True),
    sa.Column('amafarangaYose', sa.Integer(), nullable=True),
    sa.Column('amafarangaYoGutonoza', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umusarurob',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RiceType', sa.String(length=100), nullable=True),
    sa.Column('UmusaruroGrade', sa.Integer(), nullable=True),
    sa.Column('RiceAmount', sa.Integer(), nullable=True),
    sa.Column('UwoAsigaranye', sa.Float(), nullable=True),
    sa.Column('UwoKugurisha', sa.Integer(), nullable=True),
    sa.Column('GutonozaAmount', sa.Integer(), nullable=True),
    sa.Column('AmafarangaUmusaruro1', sa.Integer(), nullable=True),
    sa.Column('Asigaye', sa.Float(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abishyuwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_payed', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=200), nullable=True),
    sa.Column('ibiro', sa.Float(), nullable=True),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.Column('umusaruro_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['umusaruro_id'], ['umusarurob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abishyuwe')
    op.drop_table('umusarurob')
    op.drop_table('umusaruro')
    op.drop_table('umusanzu')
    op.drop_table('profiles')
    op.drop_table('motos')
    op.drop_table('itsindamember')
    op.drop_table('inyongeramusaruro')
    op.drop_table('ibyakoreshejwe')
    op.drop_table('ibirarane')
    op.drop_table('ibindi')
    op.drop_table('ibihano')
    op.drop_table('coopMemberBankAccounts')
    op.drop_table('contributions')
    op.drop_table('CRMs')
    op.drop_table('zones')
    op.drop_table('umugabaneShingiro')
    op.drop_table('ububiko')
    op.drop_table('members')
    op.drop_table('isandukunshya')
    op.drop_table('inkunga')
    op.drop_table('inguzanyozabandi')
    op.drop_table('ikoreshwaRyimari')
    op.drop_table('ibiramba')
    op.drop_table('ibindiRukomatanya')
    op.drop_table('ibicuruzwa')
    op.drop_table('bank')
    op.drop_table('InguzanyoZatanzwe')
    # ### end Alembic commands ###
