"""empty message

Revision ID: c1eb8dc85fab
Revises: fe5a4164eb99
Create Date: 2020-01-09 13:18:09.075154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1eb8dc85fab'
down_revision = 'fe5a4164eb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'budgetcategory', ['Category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgetcategory', type_='unique')
    # ### end Alembic commands ###
