"""empty message

Revision ID: c4322a536e51
Revises: 
Create Date: 2018-11-13 15:18:08.995457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4322a536e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umusanzu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UmusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('UmusanzuCoop', sa.Integer(), nullable=True),
    sa.Column('Umugabane', sa.Integer(), nullable=True),
    sa.Column('Ikigega', sa.Integer(), nullable=True),
    sa.Column('KuzibaIcyuho', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('umusanzu')
    # ### end Alembic commands ###
