"""empty message

Revision ID: cd1380ca0157
Revises: beaabec4f5ef
Create Date: 2020-01-18 12:56:54.790994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1380ca0157'
down_revision = 'beaabec4f5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusarurob', sa.Column('Avance', sa.Integer(), nullable=True))
    op.add_column('umusarurob', sa.Column('Carnet', sa.Integer(), nullable=True))
    op.add_column('umusarurob', sa.Column('Musa', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('umusarurob', 'Musa')
    op.drop_column('umusarurob', 'Carnet')
    op.drop_column('umusarurob', 'Avance')
    # ### end Alembic commands ###
