"""empty message

Revision ID: cf0d2c1b4256
Revises: cabcd0da8f1b
Create Date: 2019-01-31 05:07:10.515464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0d2c1b4256'
down_revision = 'cabcd0da8f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amatsinda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itsinda_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amatsinda')
    # ### end Alembic commands ###
