"""empty message

Revision ID: d252444889f6
Revises: 16610378222a
Create Date: 2019-06-01 15:34:40.024001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd252444889f6'
down_revision = '16610378222a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('education_level', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'education_level')
    # ### end Alembic commands ###
