"""empty message

Revision ID: d9ae66dbf38b
Revises: b158cf0671f5
Create Date: 2020-01-16 12:53:30.737927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ae66dbf38b'
down_revision = 'b158cf0671f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('Period', sa.String(length=200), nullable=True))
    op.add_column('budget', sa.Column('Title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'Title')
    op.drop_column('budget', 'Period')
    # ### end Alembic commands ###
