"""empty message

Revision ID: dbdb4d972aeb
Revises: 23d7aff2651a
Create Date: 2020-01-08 11:42:52.133173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbdb4d972aeb'
down_revision = '23d7aff2651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'ubwoko_igihingwa')
    op.drop_column('members', 'ubuso_ahingaho')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('ubuso_ahingaho', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('members', sa.Column('ubwoko_igihingwa', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
