"""empty message

Revision ID: e6a2afa6b148
Revises: 598fb8769ad2
Create Date: 2018-12-24 09:58:28.868704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6a2afa6b148'
down_revision = '598fb8769ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs')
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.create_table('subs',
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.VARCHAR(length=399), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], name='subs_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='subs_ibfk_2'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
