"""empty message

Revision ID: e89d8840c37d
Revises: 323fcffb3d9b
Create Date: 2018-11-13 13:44:42.158975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e89d8840c37d'
down_revision = '323fcffb3d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inyongeramusaruro', 'umwakaWisarura')
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.add_column('inyongeramusaruro', sa.Column('umwakaWisarura', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
