"""empty message

Revision ID: e99df59d8017
Revises: 99de89dedde9
Create Date: 2020-01-10 13:51:29.710771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e99df59d8017'
down_revision = '99de89dedde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('Description', sa.String(length=200), nullable=True))
    op.drop_column('expense', 'Desciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('Desciption', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('expense', 'Description')
    # ### end Alembic commands ###
