"""empty message

Revision ID: ea8216134708
Revises: 6e876ec1df7d
Create Date: 2019-02-03 17:14:35.198406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8216134708'
down_revision = '6e876ec1df7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibicuruzwa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ayinjiye', sa.Integer(), nullable=True),
    sa.Column('ayasohotse', sa.Integer(), nullable=True),
    sa.Column('asigaye', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibicuruzwa')
    # ### end Alembic commands ###
