"""empty message

Revision ID: eac52412ec5a
Revises: f4fc427385b3
Create Date: 2018-11-13 17:09:47.959795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eac52412ec5a'
down_revision = 'f4fc427385b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibihano', sa.Column('comment', sa.String(length=200), nullable=True))
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('ibihano', 'comment')
    # ### end Alembic commands ###
