"""empty message

Revision ID: eceb0572f264
Revises: 68589004c420
Create Date: 2019-02-23 09:15:41.789986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceb0572f264'
down_revision = '68589004c420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_accountant', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('is_production_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_production_manager')
    op.drop_column('employees', 'is_manager')
    op.drop_column('employees', 'is_accountant')
    # ### end Alembic commands ###
