"""empty message

Revision ID: f4fc427385b3
Revises: 629271110dca
Create Date: 2018-11-13 17:05:13.740220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4fc427385b3'
down_revision = '629271110dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibihano', sa.Column('AmandeApII', sa.Integer(), nullable=True))
    op.add_column('ibihano', sa.Column('AmandeC', sa.Integer(), nullable=True))
    op.drop_column('ibihano', 'Igihano')
    op.drop_column('ibihano', 'comment')
    op.drop_column('ibihano', 'IgihanoAmount')
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unions', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.add_column('ibihano', sa.Column('IgihanoAmount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ibihano', sa.Column('comment', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ibihano', sa.Column('Igihano', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('ibihano', 'AmandeC')
    op.drop_column('ibihano', 'AmandeApII')
    # ### end Alembic commands ###
