"""empty message

Revision ID: f7b4a959023c
Revises: 25d8b88daf1c
Create Date: 2019-01-31 18:05:48.917340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b4a959023c'
down_revision = '25d8b88daf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itsindamember', sa.Column('itsinda_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itsindamember', 'itsinda_name')
    # ### end Alembic commands ###
