"""empty message

Revision ID: fa6337bdbb1b
Revises: d9ae66dbf38b
Create Date: 2020-01-20 11:00:53.686924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa6337bdbb1b'
down_revision = 'd9ae66dbf38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('Account', sa.String(length=200), nullable=True))
    op.add_column('expense', sa.Column('Budget', sa.String(length=200), nullable=True))
    op.drop_column('expense', 'Account')
    op.add_column('expensecategory', sa.Column('Category', sa.String(length=200), nullable=True))
    op.drop_column('expensecategory', 'AccountName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expensecategory', sa.Column('AccountName', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('expensecategory', 'Category')
    op.add_column('expense', sa.Column('Account', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('expense', 'Budget')
    op.drop_column('budget', 'Account')
    # ### end Alembic commands ###
