"""empty message

Revision ID: fb737083fd24
Revises: 
Create Date: 2018-11-27 06:55:26.954936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb737083fd24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibirarane', sa.Column('Briquette', sa.Integer(), nullable=True))
    op.add_column('ibirarane', sa.Column('BriquettePerUnity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibirarane', 'BriquettePerUnity')
    op.drop_column('ibirarane', 'Briquette')
    # ### end Alembic commands ###
