"""empty message

Revision ID: fcaba37a8498
Revises: 
Create Date: 2019-01-02 20:19:54.334593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcaba37a8498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committees')
    op.drop_table('subs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.VARCHAR(length=399), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.email'], name=u'subs_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_id'], [u'employees.id'], name=u'subs_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('committees',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('nid', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('sector', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('yob', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('committee', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('education', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('monthly_net_salary', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('department_id', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.email'], name=u'committees_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
