"""empty message

Revision ID: fe5a4164eb99
Revises: c38f5cb21800
Create Date: 2020-01-09 11:19:37.028846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5a4164eb99'
down_revision = 'c38f5cb21800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Category', table_name='budgetcategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('Category', 'budgetcategory', ['Category'], unique=True)
    # ### end Alembic commands ###
